title: Site
unlisted: true
templates:
  - issue
  - error

tabs:

  pages:
    label: Site Overview
    sections:
      drafts:
        headline: Drafts
        type: pages
        layout: list
        status: draft
        templates: 
          - issue

      published:
        headline: Published Pages
        type: pages
        layout: list
        status: listed
        templates: 
          - issue

      
      content:
        type: fields
        fields:
          site_management:
            label: Site Management
            type: headline
          seo_image:
            label: Sitewide SEO Image
            type: files
            multiple: false
            width: 1/2
          favicon:
            label: Favicon
            type: files
            multiple: false
            help: png file at 160px x 160px
            width: 1/2
          seo_description:
            label: SEO Site Description
            type: textarea
            size: small
            width: 1/3
          seo_tags:
            label: SEO Site Keywords
            type: tags
            width: 1/3
          googleanalytics:
            label: Google Analytics
            type: textarea
            font: monospace
            size: medium
            width: 1/3

  content:
    label: Homepage
    type: fields
    fields:
      homepage_view:
        label: Homepage View
        type: headline
      homepage_order:
        label: Menu
        type: pages
        query: site.children.template("issue")
        layout: cards
        size: small
      site_section:
        label: Site Contents
        type: headline
      site_text:
        label: Site Body
        type: textarea
        size: large
      footer_view:
        label: Footer
        type: headline
      credit_columns:
        label: Credit Columns
        type: structure
        width: 1/2
        fields:
          column_title:
            label: Column Title
            type: text
          column_contents:
            label: Column Contents
            type: textarea
            size: medium
      footer_links:
        label: Footer Links
        help: Social Links
        type: structure
        width: 1/2
        fields:
          link_url:
            label: Link URL
            type: url
            width: 1/2
          link_name: 
            label: Link Title
            type: text
            width: 1/2
      emailform:
        label: Email Form
        type: textarea
        font: monospace
        size: medium
        width: 1/2
      footer_copyright:
        label: Copyright
        type: text
        width: 1/2